### ISSUE TITLE
Question: About Proxy

### ISSUE THREAD

**Issue by sampatsharma143** [ghoshRitesh12/aniwatch#3]
Do we need to add proxy or hianime.to does not ban any ip ?

**Comment by ghoshRitesh12** [comment]
This API has been active since 1 year and haven't faced any IP ban issues since. So it's safe to assume that hianime doesn't ban IPs.

**Comment by sampatsharma143** [comment]
can you share your traffic count ? thank you.

**Comment by sampatsharma143** [comment]
okay, thanks for sharing this much, i guess i will have to check on production can you tell me , if i have to implement proxy i will just have to implement it in the client.ts only  ?

**Comment by ghoshRitesh12** [comment]
Since this is just a library do it however you want. It isn't opinionated. Also you can use this https://github.com/itzzzme/m3u8proxy for streaming links i.e. m3u8 proxy.

**Comment by sampatsharma143** [comment]
Thanks for sharing this but i use this in my other project : https://github.com/warren-bank/HLS-Proxy

**Comment by ghoshRitesh12** [comment]
Thanks for sharing that too.
