### ISSUE TITLE
Unable to fetch full information on getAnimeEpisodeSources

### ISSUE THREAD

**Issue by Subhajeetch** [ghoshRitesh12/aniwatch#4]
### Describe the bug

I'm unable to fetch getAnimeEpisodeSources data, it was working pretty well yesterday. I checked today it doesn't working. I don't know what's wrong maybe I should wait or I could really use an explanation right now.

### Expected behavior

**Yesterday it was giving me full data... Like this:** 
{
  headers: {
    Referer: string,
    "User-Agent": string,
    ...
  },
  sources: [
    {
      url: string, // .m3u8 hls streaming file
      isM3U8: boolean,
      quality?: string,
    },
    {...}
  ],
  subtitles: [
    {
      lang: "English",
      url: string, // .vtt subtitle file
    },
    {...}
  ],
  anilistID: number | null,
  malID: number | null,
}

### Actual behavior

**Today it's happening like this:** 
{
  "tracks": [],
  "sources": [],
  "anilistID": 16498,
  "malID": 16498
}

**Here is a picture:**
![Screenshot_20241210-165026](https://github.com/user-attachments/assets/e90b7ae8-bf0f-4e26-8b86-342d940e22c6)

### Additional context

I tried again & again, but getting the same issue. So i reached out to you. Thank you for making this scrapper appreciate it.

**Comment by ghoshRitesh12** [comment]
I think you have to wait a while for this one

**Comment by Subhajeetch** [comment]
Umm hey, not just here but in the consumet APIs too... 
It seems mega cloud made some changes... I reached out to people on discord as well they said the same thing. 

One of them said this:
![Screenshot_20241211-012340](https://github.com/user-attachments/assets/a9f537cc-73f5-4a53-8a95-9af81c4b4ba8)
He is talking about the consumet's megacloud.ts file.

Thanks again!

**Comment by Subhajeetch** [comment]
Hope it'll be fixed soon

**Comment by ghoshRitesh12** [comment]
🤞🏼

**Comment by Andro999b** [comment]
Megacloud now uses wasm compiled modules to calc pid, ktime and kversion. Some tries to do workaround here: https://github.com/drblgn/rabbit_wasm/tree/main. But its looks complicated now.

**Comment by ghoshRitesh12** [comment]
Closing this issue, as it's fixed now.
